valor = input('Digite alguma coisa: ')
print('O tipo primitivo deste valor e: ', type(valor))
print('Valor digitado tem somente espacos? ', valor.isspace())
print('Valor e um numero? ', valor.isnumeric())
print('Valor e alfabetico? ', valor.isalpha())
print('Valor e alfanumerico? ', valor.isalnum())
print('Esta em MAISUCULAS? ', valor.isupper())
print('Esta em MAISUCULAS? ', valor.isupper())
print('Esta em minusculas? ', valor.islower())
print('Esta em Capilalizada? ', valor.istitle())
